CREATE TABLE IF NOT EXISTS `HOST` (
  `IDX` bigint NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `HOST` varchar(50) NOT NULL,
  `TYPE` VARCHAR(10) NOT NULL, 
  `TOPIC` varchar(100) DEFAULT NULL,
  `HOST_ID` varchar(30) DEFAULT NULL,
  `PASSWORD` varchar(200) DEFAULT NULL,
  `CREATE_DT` datetime NOT NULL,
  `CREATE_AT` varchar(100) NOT NULL,
  `UPDATE_DT` datetime NOT NULL,
  `UPDATE_AT` varchar(100) NOT NULL,
  PRIMARY KEY (`IDX`)
);

CREATE TABLE IF NOT EXISTS `FORMAT` (
  `IDX` bigint NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `FORMAT` clob NOT NULL,
  `CONTENT_TYPE` varchar(50) DEFAULT NULL,
  `CREATE_DT` datetime NOT NULL,
  `UPDATE_DT` datetime NOT NULL,
  `CREATE_AT` varchar(100) NOT NULL,
  `UPDATE_AT` varchar(100) NOT NULL,
  PRIMARY KEY (`IDX`)
);

CREATE TABLE IF NOT EXISTS `USER` (
  `USERNAME` varchar(100) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `CREATE_DT` datetime DEFAULT NULL,
  `UPDATE_DT` datetime DEFAULT NULL,
  `CREATE_AT` varchar(100) DEFAULT NULL,
  `UPDATE_AT` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`USERNAME`)
);